# Site settings
title: jProjects
email: jerryq27@gmail.com
description: "My corner of the web to discuss my projects :)"
baseurl: ""
url: ""
title_description: "My project site"
title_image: /assets/img/title_image.png
images: /assets/img
google_analytics: ""
github_repository: https://github.com/jerryq27/jerryq27.github.io
post_limit: 5

collections:
  projects:
    output: true
    permalink: /:collection/:name
  demos:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true

permalink: pretty
exclude: [vendor]
