# Site settings
title: jProjects
email: jerryq27@gmail.com
description: "Just another developer's blog."
baseurl: ""
url: ""
title_description: "Just another developer's blog."
title_image: assets/img/title_image.png
google_analytics: "UA-20365477-4"
disqus_account:
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: jerryq27
github_username:  jerryq27
instagram_username: jerryq27
reddit_username:
linkedin_link: https://linkedin.com/in/gerardo-quintero-3aab4010a
stackoverflow_link: https://stackoverflow.com/users/4052494/jerryq27
xing_link:
facebook_link:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
