services:
  jprojects-site:
    image: env_webdev
    container_name: projects_jprojects-site
    pull_policy: missing
    stdin_open: true
    tty: true
    user: "1000:1000"
    volumes:
      - ./:/home/webdev/app/
      - dependencies:/usr/local/bundle
    ports:
      - 4000:4000
      - 4001:4001
volumes:
  dependencies: {}

