services:
  jekyll:
    image: ruby:3.4-rc
    container_name: ghpages_jekyll
    working_dir: /app
    volumes:
      - .:/app
      - dependencies:/usr/local/bundle
    ports:
      - 4000:4000
      - 4001:4001
    # user: 1000:1000
    restart: always
    command: ["bash", "init.sh"]
volumes:
  dependencies: {}

